"""Write the two tables the Aether client needs to count usable abstracts exactly as Python does.

    python clients/aether/tools/gen_tables.py

The Python client counts the words of ``text.lower()`` with the pattern
``[^\\W\\d_]+`` and checks them against its stop-word list. Aether has no
Unicode character database, so this script writes what Python's own one
says into ``src/letters.ae`` (the code points that pattern counts as
letters) and copies the stop-word list into ``src/stopwords.ae``. It has
to be Python: the tables must say what the Python client's ``re`` and
``str.lower`` say. Run it with the Python version the reference client
uses, and again when that version's Unicode tables change.
"""

from __future__ import annotations

import importlib.util
import re
import sys
import unicodedata
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
STOPWORDS_PY = HERE.parent / "python" / "undiscovered" / "stopwords.py"
LETTER = re.compile(r"[^\W\d_]")


def is_letter(ch: str) -> bool:
    return LETTER.fullmatch(ch) is not None


def letter_ranges() -> list[tuple[int, int]]:
    """Non-ASCII code points that are letters once lowered, as inclusive ranges.

    Checks the assumptions the Aether tokenizer relies on, so that a Unicode
    update that breaks one stops here instead of producing a wrong table.
    """
    ranges: list[tuple[int, int]] = []
    start = prev = None
    for cp in range(0x80, 0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        low = ch.lower()
        if cp == 0x130:
            assert low == "i̇" and not is_letter("̇"), "U+0130 lowers to i + U+0307"
        elif cp == 0x212A:
            assert low == "k", "U+212A (Kelvin sign) lowers to k"
        else:
            assert len(low) == 1 and (ord(low) >= 0x80 or not is_letter(low)), \
                f"U+{cp:04X} lowers to {low!r}: the tokenizer does not handle that"
            assert is_letter(low) == is_letter(ch), f"lowering U+{cp:04X} changes whether it is a letter"
        if is_letter(ch):
            if start is None:
                start = cp
            prev = cp
        elif start is not None:
            ranges.append((start, prev))
            start = None
    if start is not None:
        ranges.append((start, prev))
    return ranges


def stop_words() -> list[str]:
    spec = importlib.util.spec_from_file_location("stopwords", STOPWORDS_PY)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    words = sorted(mod.ENGLISH_STOP_WORDS, key=lambda w: w.encode("utf-8"))
    assert all(re.fullmatch(r"[a-z]+", w) for w in words), "stop words are lowercase ASCII"
    return words


def write_letters(path: Path) -> None:
    ranges = letter_ranges()
    flat = [x for r in ranges for x in r]
    lines = []
    for i in range(0, len(flat), 8):
        lines.append("    " + ", ".join(f"0x{x:05X}" for x in flat[i:i + 8]))
    path.write_text(
        "// Generated by tools/gen_tables.py: do not edit.\n"
        f"// Python {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}.\n"
        "//\n"
        "// The non-ASCII code points that Python's `[^\\W\\d_]` (a letter, or a\n"
        "// number that is not a decimal digit) matches after `str.lower()`, as\n"
        "// inclusive ranges. Two code points lower to something special:\n"
        "// U+0130 to \"i\" and a combining dot (a letter, then a break), and\n"
        "// U+212A (Kelvin sign) to \"k\". Every other one keeps its class.\n"
        "\n"
        "exports(is_letter, DOTTED_CAPITAL_I, KELVIN_SIGN)\n"
        "\n"
        "const DOTTED_CAPITAL_I = 0x130\n"
        "const KELVIN_SIGN = 0x212A\n"
        f"const RANGE_COUNT = {len(ranges)}\n"
        f"const LETTER_RANGES: int[{len(flat)}] = [\n" + ",\n".join(lines) + "\n]\n"
        "\n"
        "// 1 when the code point (128 or above) counts as a letter, else 0.\n"
        "is_letter(cp: int) -> int {\n"
        "    lo = 0\n"
        "    hi = RANGE_COUNT\n"
        "    while lo < hi {\n"
        "        mid = (lo + hi) / 2\n"
        "        if cp < LETTER_RANGES[2 * mid] {\n"
        "            hi = mid\n"
        "        } else if cp > LETTER_RANGES[2 * mid + 1] {\n"
        "            lo = mid + 1\n"
        "        } else {\n"
        "            return 1\n"
        "        }\n"
        "    }\n"
        "    return 0\n"
        "}\n",
        encoding="utf-8", newline="\n")
    print(f"{len(ranges)} letter ranges -> {path}")


def word_key(word: str) -> int:
    """A lowercase ASCII word as a number: its letters a=1 .. z=26 as base-27 digits."""
    key = 0
    for c in word:
        key = key * 27 + ord(c) - 96
    return key


def write_stopwords(path: Path) -> None:
    words = sorted(stop_words(), key=word_key)
    longest = max(len(w) for w in words)
    assert 27 ** longest < 2 ** 63, "the keys fit a long"
    lines = [f"    {word_key(w)},{' ' * (20 - len(str(word_key(w))))}// {w}" for w in words]
    lines[-1] = lines[-1].replace(",", " ", 1)
    path.write_text(
        "// Generated by tools/gen_tables.py: do not edit.\n"
        "//\n"
        "// The English stop-word list of clients/python/undiscovered/stopwords.py\n"
        "// (scikit-learn's). Each word is kept as a number, its letters a=1 .. z=26\n"
        "// read as base-27 digits, so the tokenizer can check a word as it reads\n"
        "// it, without building a string. Sorted for a binary search.\n"
        "\n"
        "exports(is_stop_key, LONGEST)\n"
        "\n"
        f"const COUNT = {len(words)}\n"
        f"const LONGEST = {longest}\n"
        f"const KEYS: long[{len(words)}] = [\n" + "\n".join(lines) + "\n]\n"
        "\n"
        "// 1 when `key` is the key of a stop word, else 0.\n"
        "is_stop_key(key: long) -> int {\n"
        "    lo = 0\n"
        "    hi = COUNT\n"
        "    while lo < hi {\n"
        "        mid = (lo + hi) / 2\n"
        "        if KEYS[mid] == key {\n"
        "            return 1\n"
        "        }\n"
        "        if KEYS[mid] < key {\n"
        "            lo = mid + 1\n"
        "        } else {\n"
        "            hi = mid\n"
        "        }\n"
        "    }\n"
        "    return 0\n"
        "}\n",
        encoding="utf-8", newline="\n")
    print(f"{len(words)} stop words -> {path}")


if __name__ == "__main__":
    write_letters(HERE / "src" / "letters.ae")
    write_stopwords(HERE / "src" / "stopwords.ae")
